version: "3"
services:
    frontend:
        container_name: billsplit_client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: roshanv99/billsplit_client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: billsplit_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: roshanv99/billsplit_server
        ports:
          - "5001:5001"
        volumes:
          - ./server:/usr/src/app